"aegis_cloud": "azure"
"aegis_data_devices":
- "dev": "/dev/sdc"
  "fs": "ext4"
  "mount": "/var/lib/postgresql"
  "name": "pgsql"
- "dev": "/dev/sdd"
  "fs": "xfs"
  "mount": "/var/lib/mongodb"
  "name": "mongo"
- "dev": "/dev/sdb"
  "fs": "ext4"
  "mount": "/var/lib/redis"
  "name": "redis"
"aegis_raid_devices": []
