"aegis_cloud": "azure"
"aegis_data_devices":
- "fs": "xfs"
  "lun": 0
  "mount": "/var/lib/kafka/data0"
  "name": "kafka_jbod0"
- "fs": "xfs"
  "lun": 1
  "mount": "/var/lib/kafka/data1"
  "name": "kafka_jbod1"
"aegis_raid_luns": []
"aegis_region": "australiasoutheast"
