apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: metrics-server
        resources:
          requests:
            cpu: 50m
            memory: 80Mi
          limits:
            cpu: 200m
            memory: 200Mi
