---
- name: Setup Application Node (Ingress & Bastion)
  hosts: app_nodes
  become: yes
  roles:
    - 02-kernel
    - 03-security
    - 04-runtime
    - 06-stateful-tier
    - 07-observability

- name: Setup Database Node (I/O Isolated Storage)
  hosts: db_nodes
  become: yes
  roles:
    - 01-storage
    - 02-kernel
    - 03-security
    - 06-stateful-tier
    - 07-observability

- name: Setup Kafka Message Broker (RAID 5)
  hosts: kafka_nodes
  become: yes
  roles:
    - 01-storage
    - 02-kernel
    - 03-security
    - 06-stateful-tier
    - 07-observability

- name: Setup Observability Central Server
  hosts: monitor_nodes
  become: yes
  roles:
    - 01-storage
    - 02-kernel
    - 03-security
    - 07-observability
