replicaCount: 1

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: demo-app.local
  path: /

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  enabled: true
  readiness:
    path: /
    initialDelaySeconds: 3
    periodSeconds: 5
  liveness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10

securityContext:
  allowPrivilegeEscalation: false

config:
  logLevel: info
