apiVersion: apps/v1
kind: Deployment
metadata:
  name: drain-demo
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drain-demo
  template:
    metadata:
      labels:
        app: drain-demo
    spec:
      containers:
      - name: app
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
