---
- name: Отключение Swap (runtime)
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Отключение Swap в fstab (persistence)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Загрузка модулей ядра
  modprobe:
    name: "{{ item }}"
    state: present
  loop: [overlay, br_netfilter, tcp_bbr]

- name: Персистентная загрузка модулей
  copy:
    dest: /etc/modules-load.d/aegis.conf
    content: |
      overlay
      br_netfilter
      tcp_bbr

- name: Создание Systemd Unit для отключения Transparent Huge Pages (THP)
  copy:
    dest: /etc/systemd/system/disable-thp.service
    content: |
      [Unit]
      Description=Disable Transparent Huge Pages (THP)
      DefaultDependencies=no
      After=sysinit.target local-fs.target

      [Service]
      Type=oneshot
      ExecStart=/bin/sh -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled; echo never > /sys/kernel/mm/transparent_hugepage/defrag'

      [Install]
      WantedBy=basic.target
  when: "'stateful' in group_names"

- name: Включение сервиса отключения THP
  systemd:
    name: disable-thp.service
    enabled: yes
    state: started
  when: "'stateful' in group_names"

- name: Общий Тюнинг сети и BBR
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-aegis-prod.conf
    state: present
    reload: yes
  loop:
    - { key: 'net.core.default_qdisc', value: 'fq' }
    - { key: 'net.ipv4.tcp_congestion_control', value: 'bbr' }
    - { key: 'net.core.somaxconn', value: '65535' }
    - { key: 'net.ipv4.ip_local_port_range', value: '1024 65535' }
    - { key: 'fs.file-max', value: '2000000' }
    - { key: 'vm.swappiness', value: '0' }

- name: Тюнинг для PostgreSQL, Redis и MongoDB
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-db-tuning.conf
    state: present
    reload: yes
  loop:
    - { key: 'vm.dirty_background_ratio', value: '5' }
    - { key: 'vm.dirty_ratio', value: '15' }
    - { key: 'vm.overcommit_memory', value: '1' }
    - { key: 'vm.zone_reclaim_mode', value: '0' }
  when: "'db_nodes' in group_names"

- name: Тюнинг для Kafka (Page Cache Optimization)
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-kafka-tuning.conf
    state: present
    reload: yes
  loop:
    - { key: 'vm.dirty_background_ratio', value: '5' }
    - { key: 'vm.dirty_ratio', value: '60' }
    - { key: 'vm.max_map_count', value: '262144' }
  when: "'kafka_nodes' in group_names"
