apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
  namespace: lab
spec:
  storageClassName: does-not-exist
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
