# =============================================================================
# Render Ansible inventory + per-host disk facts directly from Terraform state.
# Eliminates manual edits to hosts.ini after every apply.
# =============================================================================

locals {
  azure_bastion_ip = azurerm_public_ip.bastion.ip_address
  azure_app_ip     = azurerm_public_ip.app.ip_address
  azure_db_ip      = azurerm_network_interface.db.private_ip_address

  gcp_kafka_ip = (
    var.gcp_expose_ssh_publicly
    ? google_compute_instance.kafka.network_interface[0].access_config[0].nat_ip
    : google_compute_instance.kafka.network_interface[0].network_ip
  )
  gcp_monitor_ip = (
    var.gcp_expose_ssh_publicly
    ? google_compute_instance.monitor.network_interface[0].access_config[0].nat_ip
    : google_compute_instance.monitor.network_interface[0].network_ip
  )
}

resource "local_file" "ansible_inventory" {
  filename        = var.ansible_inventory_path
  file_permission = "0644"
  content         = <<-EOT
    # Generated by Terraform — do not edit by hand.
    [bastion]
    aegis-bastion ansible_host=${local.azure_bastion_ip}

    [app_nodes]
    aegis-app ansible_host=${local.azure_app_ip}

    [db_nodes]
    aegis-db ansible_host=${local.azure_db_ip}

    [kafka_nodes]
    aegis-kafka ansible_host=${local.gcp_kafka_ip}

    [monitor_nodes]
    aegis-monitor ansible_host=${local.gcp_monitor_ip}

    [azure_nodes:children]
    bastion
    app_nodes
    db_nodes

    [gcp_nodes:children]
    kafka_nodes
    monitor_nodes

    [stateful:children]
    db_nodes
    kafka_nodes

    [all:vars]
    ansible_user=${var.vm_admin_user}
    ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null'
  EOT
}

# Per-host disk facts. Roles read these via `aegis_data_devices` + `aegis_raid_devices`.
resource "local_file" "host_vars_app" {
  filename = "${var.ansible_host_vars_dir}/aegis-app.yml"
  content = yamlencode({
    aegis_cloud        = "azure"
    aegis_data_devices = [{ name = "app", dev = "/dev/sdc", fs = "ext4", mount = "/var/log/app_data" }]
    aegis_raid_devices = []
  })
}

resource "local_file" "host_vars_db" {
  filename = "${var.ansible_host_vars_dir}/aegis-db.yml"
  content = yamlencode({
    aegis_cloud = "azure"
    aegis_data_devices = [
      { name = "pgsql", dev = "/dev/sdc", fs = "ext4", mount = "/var/lib/postgresql" },
      { name = "mongo", dev = "/dev/sdd", fs = "xfs", mount = "/var/lib/mongodb" },
      { name = "redis", dev = "/dev/sde", fs = "ext4", mount = "/var/lib/redis" },
      { name = "etcd", dev = "/dev/sdf", fs = "ext4", mount = "/var/lib/etcd" },
    ]
    aegis_raid_devices = []
  })
}

resource "local_file" "host_vars_kafka" {
  filename = "${var.ansible_host_vars_dir}/aegis-kafka.yml"
  content = yamlencode({
    aegis_cloud        = "gcp"
    aegis_raid_devices = [for d in local.gcp_kafka_disks : "/dev/disk/by-id/google-${d}"]
    aegis_data_devices = [
      { name = "kafka", dev = "/dev/md0", fs = "xfs", mount = "/var/lib/kafka" },
    ]
  })
}

resource "local_file" "host_vars_monitor" {
  filename = "${var.ansible_host_vars_dir}/aegis-monitor.yml"
  content = yamlencode({
    aegis_cloud = "gcp"
    aegis_data_devices = [
      { name = "monitor", dev = "/dev/disk/by-id/google-m0", fs = "xfs", mount = "/var/lib/victoria-metrics-data" },
    ]
    aegis_raid_devices = []
  })
}

resource "local_file" "ssh_config" {
  filename        = "${path.module}/.generated/ssh_config"
  file_permission = "0600"
  content         = <<-EOT
    Host aegis-bastion
        HostName ${local.azure_bastion_ip}
        User ${var.vm_admin_user}
        StrictHostKeyChecking accept-new

    Host aegis-app
        HostName ${local.azure_app_ip}
        User ${var.vm_admin_user}
        StrictHostKeyChecking accept-new

    Host aegis-db
        HostName ${local.azure_db_ip}
        User ${var.vm_admin_user}
        ProxyJump aegis-bastion
        StrictHostKeyChecking accept-new

    Host aegis-kafka
        HostName ${local.gcp_kafka_ip}
        User ${var.vm_admin_user}
        StrictHostKeyChecking accept-new

    Host aegis-monitor
        HostName ${local.gcp_monitor_ip}
        User ${var.vm_admin_user}
        StrictHostKeyChecking accept-new
  EOT
}
