apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-demo
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-demo
  template:
    metadata:
      labels:
        app: net-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
