apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-web
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kb-web
  template:
    metadata:
      labels:
        app: kb-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
