#!/bin/bash

# Файл лога
LOGFILE="/var/log/zombie_killer.log"

# Поиск всех зомби-процессов
zombie_pids=$(ps axo stat,pid | awk '$1 ~ /Z/ {print $2}')

if [ -z "$zombie_pids" ]; then
  echo "[$(date)] Нет зомби-процессов." >> $LOGFILE
else
  for pid in $zombie_pids; do
    parent_pid=$(ps -o ppid= -p "$pid")
    echo "[$(date)] Обнаружен зомби-процесс PID $pid. Завершаем родительский процесс PID $parent_pid." >> $LOGFILE
    
    # Убиваем родительский процесс
    kill -9 $parent_pid
    
    # Проверяем, убит ли процесс
    if [ $? -eq 0 ]; then
      echo "[$(date)] Успешно убит зомби-процесс PID $pid и его родительский процесс PID $parent_pid." >> $LOGFILE
    else
      echo "[$(date)] Ошибка при попытке убить родительский процесс PID $parent_pid для зомби-процесса PID $pid." >> $LOGFILE
    fi
  done
fi
