[bastion]
aegis-bastion

[app_nodes]
aegis-app

[db_nodes]
aegis-db

[kafka_nodes]
aegis-kafka

[stateful:children]
db_nodes
kafka_nodes

[all:vars]
ansible_user=ansible_user
ansible_ssh_common_args='-F ~/.ssh/config'
