[app_nodes]
az-app ansible_host=4.197.147.12

[monitor_nodes]
az-app

[db_nodes]
az-db ansible_host=10.10.1.4

[kafka_nodes]
az-kafka ansible_host=10.11.1.4

[etcd_nodes]
az-etcd ansible_host=10.11.1.5

[storage_nodes]
az-storage ansible_host=10.12.1.4

[azure_nodes]
az-app
az-db
az-kafka
az-etcd
az-storage

[stateful:children]
db_nodes
kafka_nodes
etcd_nodes

[k8s_future:children]
app_nodes

[runtime_hosts:children]
app_nodes

[app_nodes:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null'

[private_nodes:children]
db_nodes
kafka_nodes
etcd_nodes
storage_nodes

[private_nodes:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null ansible_user@4.197.147.12"'

[all:vars]
ansible_user=ansible_user
ansible_ssh_private_key_file=~/.ssh/id_ed25519
