apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-readiness
  namespace: lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-readiness
  template:
    metadata:
      labels:
        app: broken-readiness
    spec:
      containers:
      - name: app
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
